### ISSUE TITLE
pyC8 - Driver fails with global dns for subscribing to DB changes

### ISSUE THREAD

**Issue by durgagokina** [Macrometacorp/pyC8#2]
Currently driver fails to subscribe to database changes when global dns is used. It works fine with the region dns.

**Comment by PNarodeMacrometa** [comment]
Pushed the fix to 0.9.6 version where, in on_change method pulsar was not able to create a connection with global dns url. So replaced the hostname with local regional url, which is fetched using dclist_local() method.
