### ISSUE TITLE
pyC8 - Driver fails to give valid permissions to user for db.

### ISSUE THREAD

**Issue by durgagokina** [Macrometacorp/pyC8#3]
Driver fails to give valid permissions to user for db. Following is the code - 
```
sys_db.create_database(demodb,dclist=dcl,users=[{'username':'demouser','password':demo_pass,'active':True}],realtime=True)
```

![image](https://user-images.githubusercontent.com/34952544/47670233-f26bcc00-db69-11e8-96cd-7061774f59f7.png)

**Comment by PNarodeMacrometa** [comment]
Was not able to reproduce the issue so looks like its working fine. Closing the ticket.
