### ISSUE TITLE
Gather a list of API changes since December

### ISSUE THREAD

**Issue by georgikiriloff** [Macrometacorp/pyC8#70]

**Comment by rahul-naik1** [comment]
**Billing**
There are lots of changes done in the 
![Screenshot from 2021-05-27 04-22-54](https://user-images.githubusercontent.com/69429748/119741403-431f3f00-bea3-11eb-9797-05944e16db39.png)
billing

**Limits**
![Uploading Screenshot from 2021-05-27 04-26-03.png…]()

**Features**
![Screenshot from 2021-05-27 04-27-30](https://user-images.githubusercontent.com/69429748/119741699-dfe1dc80-bea3-11eb-9fab-42c16eb04ffb.png)

**Federation members** (Need to check, should we include this in pyc8)
![Screenshot from 2021-05-27 04-28-07](https://user-images.githubusercontent.com/69429748/119741798-11f33e80-bea4-11eb-9cc2-56d5500bc610.png)

**Tenants**
There are lots of changes done in the request body of tenant creation

**plans**
There are lots of changes done in the request body of plan creation

**Environments**
New APIs are introduced
![Screenshot from 2021-05-27 04-32-24](https://user-images.githubusercontent.com/69429748/119742070-9ba30c00-bea4-11eb-83d8-946d05ebbfa4.png)

**Collection**
Changes in POST collection API to have flag `stream` for on-demand stream collection

**Comment by martin-macrometa** [comment]
We don't need members API in pyc8.

The following search APIs are currently not present in pyc8 (as far as I know):
```
POST ​/_fabric​/{fabric}​/_api​/search String Search
POST ​/_fabric​/{fabric}​/_api​/search​/collection​/{collection-name} Set Search Capability
```
