### ISSUE TITLE
Why does C8Client default to HTTP instead of HTTPS?

### ISSUE THREAD

**Issue by the-jesus-aviles** [Macrometacorp/pyC8#95]
Just wondering. I noticed that in the class constructor, the default protocol is plain `http`. Seems like the saner behavior (now days) would be to default to HTTPS and allow the user to specify HTTP. 

Here's the constructor I'm referring to:

https://github.com/Macrometacorp/pyC8/blob/c4288ec1c2f18f4214ab04e745fc95c6f55d8628/c8/client.py#L26

Of course, this would break things for users who are leaving this unspecified, so maybe it's not an option now anyway for backwards compatibility. 

Also, while I'm nitpicking about minor details, we make HTTP the default protocol *and* make 80 the default port, right? But if a user specifies HTTPS and then doesn't specify a port, then the port will stay at the default, right? Which is 80. So anytime you change the protocol, you almost certainly have to specify a port now. The more convenient way to do this would be to make the default port `None`, then (if it's still `None` in the constructor, meaning the user didn't specify a port), we set it to either 80 or 443 depending on the value of `protocol`. Like so:

```python3
    def __init__(self, protocol="https", host='127.0.0.1', port=None,
                 geofabric="_system", stream_port=constants.STREAM_PORT,
                 email=None, password=None,  http_client=None, token=None, apikey=None):
        if port is None: # only force the port to default if user didn't supply an explicit port
            if protocol == 'http':
               port = 80
           elif protocol == 'https':
               port = 443
           else:
               raise Exception(f'Unsupported protocol: {protocol}')
```

The current system handles this by just forcing the port to 443 if the protocol is `'https'`, no matter what the user supplies as `port`. This is actually a bug - what if the user is running HTTPS on a port other than 443? After all, that consideration is the whole reason this parameter exists for the user to supply! 

https://github.com/Macrometacorp/pyC8/blob/c4288ec1c2f18f4214ab04e745fc95c6f55d8628/c8/client.py#L38-L39

Just some thoughts! I'd be happy to submit a patch for this myself if that would be helpful. By the way, thanks for making an awesome product!

**Comment by dlozina-macrometa** [comment]
Hi @the-jesus-aviles!
Thank you very much for opening this thread. It is always lovely to get feedback on our product!
We don't mind if you would submit a patch, we can do it as well since we have a couple of upcoming upgrades on our Python SDK.

Thank you once again!
